[workspace]
members = ["crates/*"]
resolver = "2"
package.rust-version = "1.82.0"

[workspace.dependencies]
anyhow = "^1"

tauri = { version = "^2", features = ["protocol-asset", "devtools"] }
sqlx = { version = "^0.8", features = ["sqlite"] }
tokio = { version = "^1", features = ["rt"] }

serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
automerge = "^0.5"
autosurgeon = "^0.8"
log = "^0.4"
sha2 = "^0.10"
ulid = { version = "^1", features = ["serde"] }
uuid = "^1"

[workspace.dev-dependencies]
test-log = "^0.2"
env_logger = "*"