// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioType } from "./AudioType";
import type { ProjectType } from "./ProjectType";

export type AttachmentType = { "Audio": AudioType } | { "Project": ProjectType };
