// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Error enum that's directly shared with the frontend.
 */
export type BackendError = { "Other": string } | { "TempoError": string } | { "Tauri": string };
