// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Path of a folder and its validity
 */
export type FolderInfo = { path: string, error: string | null, };
