// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewAudioAttachment } from "./NewAudioAttachment";
import type { NewProjectAttachment } from "./NewProjectAttachment";

export type NewAttachment = { "Project": NewProjectAttachment } | { "Audio": NewAudioAttachment };
