// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A request from the frontend to create a comment on a note.
 */
export type NewComment = { reply_ulid: string | null, body: string, };
