// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NewAttachment } from "./NewAttachment";

/**
 * A request from the frontend to make a new note.
 */
export type NewNote = { body: string, reply_ulid: string | null, attachment: NewAttachment | null, };
