// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginRef } from "./PluginRef";

/**
 * A scan of all plugins inside of a project file and a listing of plugins that clients are missing.
 * Used when adding a project to a folder.
 */
export type PluginScan = { plugins: Array<PluginRef>, missing: { [key in string]?: Array<number> }, };
