// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginType } from "./PluginType";

export type PluginRef = { plugin_type: PluginType, name: string, vendor: string, };
