// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileRef } from "./FileRef";
import type { MissingFileRef } from "./MissingFileRef";

/**
 * Used when adding a project to a folder.
 */
export type ProjectFileRefScan = { ok: Array<FileRef>, missing: Array<MissingFileRef>, };
