// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedProjectData } from "./SharedProjectData";

/**
 * Info about a project that's been added to a Tempo folder.
 */
export type ProjectInfo = { filename: string, data: SharedProjectData, };
