// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Comment } from "./Comment";

/**
 * Repliable comment on a note.
 * Only one level of replies is supported.
 */
export type RepliableComment = { comment: Comment, replies: { [key in string]?: Comment }, };
