// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SharedAudioAttachment } from "./SharedAudioAttachment";
import type { SharedProjectAttachment } from "./SharedProjectAttachment";

export type SharedAttachment = { "Project": SharedProjectAttachment } | { "Audio": SharedAudioAttachment };
