// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from "./FileType";

/**
 * A stripped down `FileInfo`
 */
export type SharedFileInfo = { filename: string, added_by: string, timestamp: bigint, file_type: FileType, };
