// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginRef } from "./PluginRef";

/**
 * Scanned information about a project in a a Tempo Folder
 */
export type SharedProjectData = { "Ableton": { missing_files: Array<string>, missing_plugins: Array<PluginRef>, } };
