// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFileInfo } from "./AudioFileInfo";
import type { ProjectInfo } from "./ProjectInfo";
import type { TempoResult } from "./TempoResult";

export type SharedProjectAttachment = { title: string, project: TempoResult<ProjectInfo>, render: TempoResult<AudioFileInfo> | null, };
