// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioFileInfo } from "./AudioFileInfo";
import type { TempoResult } from "./TempoResult";

export type SharedAudioAttachment = { title: string | null, file: TempoResult<AudioFileInfo>, };
