// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepliableComment } from "./RepliableComment";
import type { SharedAttachment } from "./SharedAttachment";

/**
 * Similar to `NoteDoc`, but contains extra information validating note's attachment (if any)
 */
export type SharedNote = { sender: string, body: string, reply_ulid: string | null, attachment: SharedAttachment | null, comments: { [key in string]?: RepliableComment }, };
