[package]
name = "tempo_fs_provider"
version = "0.1.0"
edition = "2021"

[dependencies]
tempo_db.path = "../tempo_db"
tempo_provider.path = "../tempo_provider"

anyhow.workspace = true
tauri.workspace = true