[package]
name = "tempo_provider"
version = "0.1.0"
edition = "2021"

[dependencies]
sql.workspace = true
tempo_types.workspace = true
tempo_id.workspace = true

anyhow.workspace = true
tauri.workspace = true
tokio.workspace = true